name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOFLAGS: -mod=readonly

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.3

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download license information for dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make license-cache

      - name: Check licenses
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make license-check

      - name: Check generators for unwanted diffs
        run: make check-diff

      - name: Run lint
        env:
          LINTER_FLAGS: '--timeout 5m'
        run: make lint

      - name: Run tests
        run: make test
#
#      - name: Lint Helm charts
#        id: lint
#        uses: helm/chart-testing-action@dev-v2
#        with:
#          command: lint
#          config: charts/helm_testing.yaml
